name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: flatt-security/setup-takumi-guard-npm@v1
      - uses: oven-sh/setup-bun@v2
      - name: Install docker CLI (act only)
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install -y docker.io
      - run: docker build -t ${{ github.repository }}:${{ github.sha }} .
